spring:
  application:
    name: eureka

server: 
  port: 8080

management:
  server:
    port: 8081

eureka: 
  instance: 
    hostname: localhost
  server:
    response-cache-update-interval-ms: 500
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/