spring:
  application:
    name: flights
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 6020
  
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

# zuul:
#   ribbon:
#     listOfServers: localhost:6000