spring:
  application:
    name: zuul

server:
  port: 6000

eureka:
  instance:
    # 这里用服务所在的机器名注册到Eureka当中，但是如果prefer-ip-address为true，则会用IP地址注册
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    airports:
      path: /airports/**
      serviceId: airports
      # url: http://localhost:6010/
    flights:
      path: /flights/**
      serviceId: flights
      # url: http://localhost:6020/
    sales:
      path: /sales/**
      serviceId: sales
      # url: http://localhost:6030/

# 前端页面初始化时即会调用Airports服务获得机场列表，通过Zuul代理请求时可能会导致请求超时，加大超时阈值可避免异常出现
# 该参数设置仅适用于Zuul代理的方式，转发的方式不适用
ribbon:
  ReadTimeout: 30000
  SocketTimeout: 15000

# 经由Zuul代理的请求均使用Hystrix command包装，缺省超时阈值为4000ms，这里设置为90000ms，以避免断路器打开
# 实际上，该值会参考由ribbon.ReadTimeout等在内的多个参数值代入某公式后计算出的结果值
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 90000

management:
  endpoints:
    web:
      exposure:
        include: '*'