spring:
  application:
    name: airports
  zipkin:
    base-url: http://zipkin-svc/
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080

management:
  server:
    port: 8081
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-svc/eureka/
