spring:
  application:
    name: presentation
  zipkin:
    base-url: http://zipkin-svc/
  sleuth:
    sampler:
      probability: 1.0


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-svc/eureka/


hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000

hystrix:
  threadpool:
    SalesThreads:
      coreSize: 20
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200


server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
